import argparse
import os
import sys
import json
import http.server
import map.disasm
import map.editorserver
import map.export
import npc.npc
import npc.codegen


def main(args):
    parser = argparse.ArgumentParser()
    parser.add_argument("map_json_file")
    parser.add_argument("disasm_path")
    parser.add_argument("--npcs", required=False, metavar="NPC script directory")
    parser.add_argument("--from-disasm", action="store_true")
    parser.add_argument("--to-disasm", action="store_true")
    parser.add_argument("--edit", action="store_true", help="Run the editor. Default if from/to-disasm is not specified")
    args = parser.parse_args(args)

    if args.from_disasm:
        if os.path.exists(args.map_json_file):
            print("Not overriding existing json file. Exporting is not perfect and should only be done once.")
            exit(1)
        data = map.disasm.room_data_to_json(args.disasm_path)
        json.dump(data, open(args.map_json_file, "wt"), indent="  ")
    if args.edit or (not args.from_disasm and not args.to_disasm):
        server = map.editorserver.EditorServer(args.disasm_path)
        server.load_map_json(args.map_json_file)
        try:
            server.serve_forever()
        except KeyboardInterrupt:
            pass
    if args.to_disasm:
        map.export.do_export(args.disasm_path, json.load(open(args.map_json_file, "rt")))
        if args.npcs:
            dialog_pointer_file = open(os.path.join(args.disasm_path, "src", "data", "dialogs", "generated_dialog_pointers.asm"), "wt")
            dialog_pointer_file.write("; Automatically generated by KoholintLab.\n")
            dialog_bank_file = open(os.path.join(args.disasm_path, "src", "data", "dialogs", "generated_dialog_banks.asm"), "wt")
            dialog_bank_file.write("; Automatically generated by KoholintLab.\n")
            for path, dirs, files, in os.walk(args.npcs):
                for file in files:
                    if os.path.splitext(file)[1].lower() == ".npc":
                        n = npc.npc.NPC(os.path.join(path, file))
                        print(f"Generating {n.assembly_file} from {path}/{file}")
                        cg = npc.codegen.CodeGen(n, open(os.path.join(args.disasm_path, "src", "code", "entities", n.assembly_file), "wt"))
                        for dialog_label in cg.get_dialog_labels():
                            dialog_pointer_file.write(f"  dialog_pointer {dialog_label}\n")
                            dialog_bank_file.write(f"  db BANK({dialog_label})\n")

if __name__ == "__main__":
    main(sys.argv[1:])
